config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tweets#index'
  resources :tweets
  resources :users

  # post    'momoclo/login'=>'blogs#login'
  # get     'tweets/new' =>"tweets#new"
  # post    'momoclo/complete' => 'tweets#create'
  # patch   'momoclo/:id'   =>  'tweets#update'
  # delete  'momoclo/:id' => 'tweets#destroy'
  # get     'momoclo/:id/edit'=> 'tweets#edit'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end
# <div class="box_title"><span>point</span></div><div class="box">記事は必ずユーザーと紐づいているのでbelongs_to :user</div>

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/concerns/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @tweets = Tweet.all.order("id DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(text: tweet_params[:text],user_id: current_user.id)
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweets.user_id === current_user.id
  end

  def edit
    @tweets = Tweet.find(params[:id])
    
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params) if tweet.user_id == current_user.id
end

def show
  
end

  private
  def tweet_params
    params.require(:tweet).permit(:text)
  end

  private
    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>momoclo_blog</title>

  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

  <style type="text/css" href="./style.css"></style>
 <!-- Compiled and minified CSS -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

 <!-- Compiled and minified JavaScript -->
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">ももクロブログ</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
          <%if user_signed_in? %>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete%></li>
              <li><%= link_to "投稿", new_tweet_path, class: 'post'%></li>
              <%# <li><%= link_to "投稿する", momoclo_complete_path, class: 'post'</li> %>
            <%else %>
              <li><%= link_to "ログイン", new_user_session_path, class: 'post'%></li>
              <li><%= link_to "新規登録", new_user_registration_path, class: 'post'%></li>
          <%end %>
          </ul>
        </div>
      </nav>
            

<h2>ももクロについてのつぶやき☆*:.｡. o(≧▽≦)o .｡.:*☆</h2>

<script type="text/javascript" src="./app.js"></script>
</body>
</html>
<%= yield %>

app/views/tweets/_tweet.html.erb
  <div class="row">
    <div class="col s12 m6">
      <div class="card #5e35b1 deep-purple darken-1">
        <div class="card-content white-text">
          <span class="card-title"> <%=tweet.name%></span>
          <p><%= simple_format(tweet.text) %></p>
          
        </div>
        <div class="card-action">
        <ul>
        <% if user_signed_in?  && current_user.id == tweet.user_id %>
        <li><%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %></li>
        <li><%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %></li>
        <% end %>
      </ul>
        </div>
      </div>
    </div>
  </div>
            

app/views/tweets/create.html.erb
<div class ="contents row">
  <div class ="success">
  <h3>
    投稿完了
  </h3>
  <a class="btn" href = "tweets">投稿へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<p>削除しました</p>
<%= link_to '一覧へ戻る/', "/" %>

app/views/tweets/edit.html.erb
<div class="contents row">
  <a href="/">一覧にもどる</a>
  <%= form_tag("/#{@tweets.id}", method: :patch) do %>
    <h3>
      編集する
    </h3>
    <p><input type="text" name="title" placeholder="タイトル" value="<%= @article.title %>"></p>
    <textarea name="content" placeholder="記事を編集してください" rows="10" cols="50"><%= @article.content %></textarea>
    <p><input type="submit" value="投稿"></p>
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="contents " >
  <% @tweets.each do |tweet| %>
  <%= render partial: "tweet", locals: { tweet: tweet } %>
     <% end %>
</div> 

app/views/tweets/new.html.erb
<div class ="contents row">
<h4>
  ももクロライブについての感想
  </h4>

  <a href="/">一覧に戻る</a>
  <%= form_for @tweet do |f| %>
    <%=f.text_field :text%>
    <%=f.submit "投稿"%>
  <%end %>

app/views/tweets/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/users/show.html.erb
<div class="contents row" >
    <p><%= @name %>さんの投稿一覧</p>
    <% @tweets.each do |tweet| %>
      <%= render partial: "tweets/tweet", locals: { tweet: tweet } %>
      </div>
    <% end %>
  </div>